/**
 * measuredCosts.mjs — GENERATED by `npm run measure-costs`. DO NOT EDIT.
 *
 * Per-effect GPU cost: 512x512 RGBA16F targets, worst-case contract params,
 * 8 warmup + 3x30 readback-forced draws, median ms/draw. Re-bless (re-run
 * the command) whenever a shader's cost could have changed.
 *
 * The CI gate (gl/costTiers.selfcheck.mjs) works on RATIOS to the overall
 * median, not absolute ms — the numbers stay meaningful when a different
 * GPU re-measures them.
 *
 * method: { w: 512, h: 512, warmup: 8, batches: 3, drawsPerBatch: 30, stat: 'median', params: 'max-contract-case' }
 * measuredAt: '2026-09-25T23:26:11.801Z'
 */
export const MEASURED_AT = '2026-09-25T23:26:11.801Z';
export const MEASURE_METHOD = { w: 512, h: 512, warmup: 8, batches: 3, drawsPerBatch: 30, stat: 'median', params: 'max-contract-case' };
export const MEASURED_COSTS = {
  'accum/copy': { ms: 0.3667, method: 'wall', draws: 90 },
  'accum/down': { ms: 0.4667, method: 'wall', draws: 90 },
  'accum/echo': { ms: 0.3667, method: 'wall', draws: 90 },
  'accum/fade': { ms: 0.3667, method: 'wall', draws: 90 },
  'accum/feed': { ms: 0.3667, method: 'wall', draws: 90 },
  'accum/glow': { ms: 0.3333, method: 'wall', draws: 90 },
  'accum/over': { ms: 0.3333, method: 'wall', draws: 90 },
  'builtin/grain': { ms: 0.4, method: 'wall', draws: 90 },
  'builtin/invert': { ms: 0.3667, method: 'wall', draws: 90 },
  'builtin/posterize': { ms: 0.4, method: 'wall', draws: 90 },
  'builtin/rgbSplit': { ms: 0.3667, method: 'wall', draws: 90 },
  'fx/displace': { ms: 0.4333, method: 'wall', draws: 90 },
  'fx/edge': { ms: 0.3333, method: 'wall', draws: 90 },
  'fx/grade': { ms: 0.3333, method: 'wall', draws: 90 },
  'fx/scanlines': { ms: 0.3667, method: 'wall', draws: 90 },
  'fx/solarize': { ms: 0.3333, method: 'wall', draws: 90 },
  'fx/tear': { ms: 0.3667, method: 'wall', draws: 90 },
};
