/**
 * costTiers.mjs — the cost-tier contract (backend hardening 3/6, arch Phase 3).
 * Browser-safe (no Node imports).
 *
 * Every GPU effect/pass declares its cost tier AT REGISTRATION, next to the
 * effect's own definition — never in a separate hard-coded list. The
 * governor's shed ladder (hooks/governorCuts.js) reads this registry instead
 * of hard-coded per-effect knowledge; the harness measures each effect's
 * real GPU cost (gl/debug/measureCosts.mjs) and the CI gate
 * (gl/costTiers.selfcheck.mjs) fails the build when a declaration doesn't
 * match the measurement.
 *
 * Tiers (the contract):
 *   0 — structural, never shed: compositing, present plumbing, the
 *       effectively-free audio modulation (scalar math per frame).
 *   1 — shed first: ACCUM passes, bloom extras, flow feedback, echoes.
 *       (The governor's independent perfTier1 mechanism covers exactly
 *       this set — see tier1ShedIds().)
 *   2 — quality scalers: turbulence octaves, blur radii — expensive but
 *       not shed-first.
 *   3 — cosmetic: cheap color ops (invert, posterize, scanlines, ...).
 *
 * A declaration: { tier, memoryBytes, timeMs, notes } and, for effects
 * with a memory gate, memoryGate: { minWidth, maxTaps }.
 * - memoryBytes: the effect's transient working set (extra FBOs + ring
 *   buffers) at 1080p, RGBA16F (8 B/px). An estimate, not a measurement —
 *   it exists so the governor's future event log and the X-ray guide view
 *   can name the cost honestly.
 * - timeMs: the author's GPU-time estimate per full-frame pass at 1080p.
 *   Also informational; the measured value lives in
 *   effects/measuredCosts.mjs (regenerated by `npm run measure-costs`).
 * - memoryGate: the rule the renderer enforces to bound the working set
 *   (e.g. echoes: width >= 2048 → at most 3 taps). The recipe owns the
 *   enforcement; the registry owns the declaration; the selfcheck asserts
 *   they agree.
 */

export const COST_TIER_INFO = {
  0: { name: 'structural', rule: 'never shed', detail: 'compositing, present plumbing, effectively-free scalar modulation' },
  1: { name: 'shed first', rule: 'governor perfTier1 cut', detail: 'ACCUM passes, bloom extras, flow feedback, echoes' },
  2: { name: 'quality scalers', rule: 'shed after tier 1', detail: 'turbulence octaves, blur radii — expensive but not first' },
  3: { name: 'cosmetic', rule: 'shed last', detail: 'cheap color ops' },
};

const registry = new Map();

/**
 * The declaration-vs-measured mapping rule (documented in docs/COST_TIERS.md,
 * enforced by gl/costTiers.selfcheck.mjs). Ratios are measured_ms /
 * median(measured_ms over all swept effects) — relative, so a different GPU
 * re-measuring the file doesn't break the gate.
 *
 * Only tier 3 carries a cost band, because only tier 3 makes a cost claim
 * ("cosmetic — cheap"). The other tiers are semantic shed-priority claims:
 * tier 1 is "shed first" (the ACCUM chain, whose passes range from the
 * cheapest to the most expensive effect in the set), tier 2 is "expensive
 * but not shed-first" (no upper bound — this is where heavy cost is
 * allowed to live), tier 0 is structural (exempt — never shed, cost
 * irrelevant).
 */
export const TIER_COST_BANDS = {
  0: null,
  1: null,
  2: null,
  3: { maxRatio: 4, warnRatio: 2.5 },
};

function isNonNegNumber(v) {
  return typeof v === 'number' && Number.isFinite(v) && v >= 0;
}

/**
 * Declare an effect's cost tier at its registration site. Fail-closed:
 * duplicates, bad tiers, and non-numeric estimates throw, naming the id.
 */
export function registerCostTier(id, decl = {}) {
  if (typeof id !== 'string' || !id) {
    throw new Error(`[cost-tiers] registerCostTier: id must be a non-empty string`);
  }
  if (registry.has(id)) {
    throw new Error(`[cost-tiers] "${id}" is already registered — duplicate cost-tier declaration`);
  }
  const { tier, memoryBytes = 0, timeMs = 0, notes = '', memoryGate = null } = decl;
  if (!Number.isInteger(tier) || tier < 0 || tier > 3) {
    throw new Error(`[cost-tiers] "${id}": tier must be an integer 0–3 (got ${String(tier)})`);
  }
  if (!isNonNegNumber(memoryBytes)) {
    throw new Error(`[cost-tiers] "${id}": memoryBytes must be a non-negative number`);
  }
  if (!isNonNegNumber(timeMs)) {
    throw new Error(`[cost-tiers] "${id}": timeMs must be a non-negative number`);
  }
  if (memoryGate !== null) {
    if (typeof memoryGate !== 'object' || !Number.isFinite(memoryGate.minWidth) || !Number.isInteger(memoryGate.maxTaps)) {
      throw new Error(`[cost-tiers] "${id}": memoryGate must be { minWidth: number, maxTaps: int }`);
    }
  }
  registry.set(id, { id, tier, memoryBytes, timeMs, notes: String(notes || ''), memoryGate });
  return id;
}

/** The declaration for one effect id, or undefined when undeclared. */
export function getCostTier(id) {
  return registry.get(id);
}

/** Every declaration, in registration order. */
export function allCostTiers() {
  return [...registry.values()];
}

/**
 * #287 bio-drives §6.1 — the radial-fan item multiplier (the TE half of
 * the manifesto: price the limitation honestly).
 *
 * An organism always emits its `bodyLen` spine items. The symmetry trait
 * appends extras around the head:
 *   'none' / 'stamp' → +0  (bodyLen items)
 *   'bilateral'      → +2  (the mirrored wing-ladder pair)
 *   'radial-N'       → +N  (the Haeckel fan: N arms around the heading)
 *
 * The multiplier is relative to the bilateral baseline (bodyLen+2), the
 * most expensive symmetry main knows today: a radial voice costs
 * (bodyLen+N)/(bodyLen+2)x what a bilateral voice costs at the same body
 * length. Non-radial symmetry returns 1 (no fan); unknown or malformed
 * ids also return 1 — the cost model never invents cost for modes it
 * doesn't recognize.
 *
 * Declared here (not at a #287 registration site) because the
 * radial-4/6/8 enum values live in unmerged PR #333
 * (feat/287-bio-drives): the fan code itself hasn't landed on main, so
 * this ships as forward-compatible data the governor's shed ladder and
 * #333's `_organismItems` can both read. Data + selfcheck only — no
 * ladder behavior change.
 */
export function radialFanMultiplier(symmetry, bodyLen = 2) {
  const m = /^radial-(\d+)$/.exec(String(symmetry ?? ''));
  if (!m) return 1;
  const folds = parseInt(m[1], 10);
  if (!Number.isFinite(folds) || folds < 3) return 1;
  const raw = Number(bodyLen);
  const body = Math.max(1, Math.min(7, Math.round(Number.isFinite(raw) ? raw : 2)));
  return (body + folds) / (body + 2);
}

/**
 * The ids the governor's independent tier-1 shed (perfTier1) covers:
 * everything declared tier 1, in shed order. This is the list that used
 * to be hard-coded as "ACCUM" in the shed ladder's comments — now the
 * registry owns it and the ladder reads it.
 */
export function tier1ShedIds() {
  return allCostTiers()
    .filter((d) => d.tier === 1)
    .map((d) => d.id);
}

/**
 * Shed order for a set of effect ids: tier 1 first, then 2, then 3
 * (tier 0 is never shed and sorts last). Within a tier, costlier effects
 * shed first — measured cost when known, else the declared estimate.
 *
 * @param {string[]} ids
 * @param {(id: string) => number|undefined} [measuredMs] — optional
 *   measured ms lookup (effects/measuredCosts.mjs).
 * @returns {string[]} ids sorted shed-first.
 */
export function shedOrder(ids, measuredMs) {
  const costOf = (id) => {
    const m = measuredMs ? measuredMs(id) : undefined;
    if (typeof m === 'number' && Number.isFinite(m)) return m;
    const d = registry.get(id);
    return d ? d.timeMs : 0;
  };
  const rank = (id) => {
    const t = registry.get(id)?.tier ?? 3;
    return t === 0 ? 4 : t; // tier 0 never sheds: always last
  };
  return [...ids].sort((a, b) => {
    const ra = rank(a), rb = rank(b);
    if (ra !== rb) return ra - rb; // tier 1 before 2 before 3
    return costOf(b) - costOf(a); // costlier sheds first within a tier
  });
}
